### ISSUE TITLE
Publish docker images 

### ISSUE THREAD

**Issue by rajaram5** [MaastrichtU-IDS/data2services-pipeline#17]
I think it is a better option if we publish the images in hub.docker.com

**Comment by vemonet** [comment]
We will consider it when we will do proper releases, but at the moment the project is too primitive and evolving too much

**Comment by vemonet** [comment]
Most Docker images have been published to Docker Hub under my username (vemonet), we will probably create an organization soon: https://hub.docker.com/u/vemonet
